apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.component }}
  labels:
    component: {{ .Values.component }}
spec:
  containers:
    - name: frontend
      image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.component }}:{{ .Values.appVersion }}
      {{- if .Values.secretmanager }}
      envFrom:
      - secretRef:
          name: {{ .Values.component }}
      {{- end }}
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]