apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.component }}
spec:
  selector:
    component: {{ .Values.component }}
  ports:
    - protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
      port: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
